---
title: "Sexual Identity Change, SPHC 2010 Followed Up Until 2021"
author: Willi Zhang, Maya Mathur
email: willi.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(ggdag)
library(ggplot2)
library(tidyverse)
library(naniar)
library(haven)
library(finalfit)
library(survey)
library(iai)
library(mice)
library(mitools)
```

### 2. SPHC 2010, followed up to 2021
```{r}
load('/Volumes/projects/LGBT Project data/d_2010.RData')

# sexual identity in 2010
table( d_2010$F10U87G78, useNA = "always" )
d_2010$F10U87G78[ d_2010$F10U87G78 == 9 ] <- NA
d_2010$sexual_identity_2010 <- factor( ifelse( d_2010$F10U87G78 == 1, "Heterosexual", "Non-heterosexual" ),
                                       levels = c( "Heterosexual", "Non-heterosexual" ) )
table( d_2010$sexual_identity_2010, useNA = "always" )

# sexual identity in 2021
table( d_2010$F21F91, useNA = "always" )
d_2010$sexual_identity_2021 <- factor( ifelse( d_2010$F21F91 == 1, "Heterosexual", "Non-heterosexual" ),
                                       levels = c( "Heterosexual", "Non-heterosexual" ) )
table( d_2010$sexual_identity_2021, useNA = "always" )

# change in sexual identity
d_2010$identity_change <- ifelse( d_2010$sexual_identity_2010 == d_2010$sexual_identity_2021, 0, 1 )
table( d_2010$identity_change, useNA = "always" )

# age
summary( d_2010$F10alder )
d_2010$age_2010 <- d_2010$F10alder

# sex
table( d_2010$kon, useNA = "always" )
d_2010$sex <- factor( ifelse( d_2010$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2010$sex, useNA = "always" )

# country of birth
table( d_2010$fodelseland, useNA = "always" )
d_2010$country_of_birth <- factor( ifelse( d_2010$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2010$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2010$country_of_birth, useNA = "always" )

# education
table( d_2010$utbniva2010, useNA = "always" )
d_2010$education_2010 <- factor( ifelse( d_2010$utbniva2010 <= 2, "<=9 years",
                                    ifelse( d_2010$utbniva2010 <= 4, "10-12 years", ">=13 years" ) ), 
                            levels = c( "<=9 years", "10-12 years", ">=13 years" ) )
table( d_2010$education_2010, useNA = "always" )

# occupation
table( d_2010$SSYK_kl, useNA = "always" )
d_2010$occupation_2010 <- factor(
  ifelse(
    d_2010$SSYK_kl == "Yrken inom byggverksamhet och tillverkning" |
      d_2010$SSYK_kl == "Yrken inom lantbruk, trädgård, skogsbruk och fiske" |
      d_2010$SSYK_kl == "Yrken inom maskinell tillverkning och transport m.m.",
    "Manual and field trades",
    ifelse(
      d_2010$SSYK_kl == "Service-, omsorgs- och försäljningsyrken" |
        d_2010$SSYK_kl == "Yrken inom administration och kundtjänst" |
        d_2010$SSYK_kl == "Yrken med krav på kortare utbildning eller introduktion",
      "Service and support",
      ifelse(
        d_2010$SSYK_kl == "Yrken med krav på fördjupad högskolekompetens" |
          d_2010$SSYK_kl == "Yrken med krav på högskolekompetens eller motsvarande" |
          d_2010$SSYK_kl == "Chefsyrken" |
          d_2010$SSYK_kl == "Militära yrken",
        "Expertise and leadership",
        NA
      )
    )
  ),
  levels = c(
    "Manual and field trades",
    "Service and support",
    "Expertise and leadership"
  )
)
table( d_2010$occupation_2010, useNA = "always" )


d_2010_prelim <- d_2010 %>% 
  select( "sexual_identity_2010", "sexual_identity_2021", "identity_change", "age_2010", "sex", "country_of_birth", "education_2010", "occupation_2010" )
summary( d_2010_prelim )
miss_var_summary( d_2010_prelim ) # 58.0% in sexual_identity_2021, 18.3% in occupation_2010, 3.8% in sexual_identity_2010, 0.7% in education_2010

# among participants in 2021 (N = 13,613), 683 (5.0%) did not report sexual identity. Therefore, the missingness in sexual_identity_2021 was primarily due to loss to follow-up

# select study sample
d_2010_selected <- d_2010_prelim %>%
  filter( age_2010 >= 25 & age_2010 <= 45 ) # select participants aged 25-45 at baseline, because this age group, relative to younger individuals, would be relatively stable socioeconomically
summary( d_2010_selected )
nrow( d_2010_selected ) # 10,063
miss_var_summary( d_2010_selected ) # 59.3% in sexual_identity_2021, 6.7% in occupation_2010, 2.3% in sexual_identity_2010, 0.3% in education_2010

d_2010_selected_final <- d_2010_selected %>% 
  filter( !is.na( sexual_identity_2010 ), !is.na( education_2010 ) ) # remove 2.3% missingness in sexual_identity_2010 and 0.3% in education_2010
summary( d_2010_selected_final )
nrow( d_2010_selected_final ) # 9,806
miss_var_summary( d_2010_selected_final ) # 58.7% in sexual_identity_2021, 6.3% in occupation_2010


# characteristics table
explanatory =  c( "sexual_identity_2021", "sex", "age_2010", "country_of_birth", "education_2010", "occupation_2010" )
dependent = "sexual_identity_2010"

d_2010_table <- d_2010_selected_final %>%
  summary_factorlist( dependent,
                      explanatory, 
                      na_include = TRUE,
                      na_include_dependent = TRUE, 
                      total_col = TRUE,
                      add_col_totals = TRUE,
                      column = TRUE )

d_2010_table


# correlation of sexual identities in 2010 and 2021
ggplot( d_2010_selected_final %>% filter( !is.na( sexual_identity_2021 ) ),
        aes( x = sexual_identity_2010, fill = sexual_identity_2021 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2010", y = "Percentage", fill = "Sexual Identity in 2021" ) +
  theme_classic()

# correlation of sexual identity in 2010 and missingness of sexual identity in 2021
ggplot( d_2010_selected_final,
        aes( x = sexual_identity_2010, fill = is.na( sexual_identity_2021 ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2010", y = "Percentage", fill = "Missingness of Sexual Identity in 2021" ) +
  theme_classic()

# correlation of sexual identity in 2010 and education
ggplot( d_2010_selected_final,
        aes( x = education_2010, fill = sexual_identity_2010 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Education Year", y = "Percentage", fill = "Sexual Identity in 2010" ) +
  theme_classic()

# correlation of sexual identity in 2010 and occupation
ggplot( d_2010_selected_final %>% filter( !is.na( occupation_2010 ) ),
        aes( x = sexual_identity_2010, fill = occupation_2010 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2010", y = "Percentage", fill = "Occupation" ) +
  theme_classic()

# correlation of sexual identity in 2010 and missingness of occupation
ggplot( d_2010_selected_final,
        aes( x = sexual_identity_2010, fill = is.na( occupation_2010 ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2010", y = "Percentage", fill = "Missingness of Occupation" ) +
  theme_classic()

# correlation of education and sexual identity in 2021
ggplot( d_2010_selected_final %>% 
          filter( !is.na( sexual_identity_2021 ) ),
        aes( x = education_2010, fill = sexual_identity_2021 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Education Year", y = "Percentage", fill = "Sexual Identity in 2021" ) +
  theme_classic()

# correlation of education and missingness of sexual identity in 2021
ggplot( d_2010_selected_final,
        aes( x = education_2010, fill = is.na( sexual_identity_2021 ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Education Year", y = "Percentage", fill = "Missingness of Sexual Identity in 2021" ) +
  theme_classic()

# correlation of education and occupation
ggplot( d_2010_selected_final %>% filter( !is.na( occupation_2010 ) ),
        aes( x = education_2010, fill = occupation_2010 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Education Year", y = "Percentage", fill = "Occupation" ) +
  theme_classic()

# correlation of education and missingness of occupation
ggplot( d_2010_selected_final,
        aes( x = education_2010, fill = is.na( occupation_2010 ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Education Year", y = "Percentage", fill = "Missingness of Occupation" ) +
  theme_classic()

# correlation of occupation and sexual identity in 2021
ggplot( d_2010_selected_final %>% 
          filter( !is.na( sexual_identity_2021 ) & !is.na( occupation_2010 ) ),
        aes( x = sexual_identity_2021, fill = occupation_2010 ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Sexual Identity in 2021", y = "Percentage", fill = "Occupation" ) +
  theme_classic()

# correlation of occupation and missingness of sexual identity in 2021
ggplot( d_2010_selected_final %>%
          filter( !is.na( occupation_2010 ) ),
        aes( x = occupation_2010, fill = is.na( sexual_identity_2021 ) ) ) +
  geom_bar( position = "fill" ) +
  scale_y_continuous( labels = scales::percent ) +
  labs( x = "Occupation", y = "Percentage", fill = "Missingness of Sexual Identity in 2021" ) +
  theme_classic()
```

### 3. Complete-case analysis
```{r}
d_cc <- d_2010_selected_final %>% 
  select( sexual_identity_2010, identity_change ) %>%
  filter( !is.na( identity_change )  )
nrow( d_cc )
summary( d_cc )
table( d_cc$identity_change )

design <- svydesign( ids = ~ 1, data = d_cc ) # simple random sampling design
poisson_robust_model <- svyglm( identity_change ~ sexual_identity_2010,
                                design = design,
                                family = quasipoisson( link = "log" ) )

summary( poisson_robust_model )

round(
  exp( cbind( coef( poisson_robust_model )[ 2 ],
              confint( poisson_robust_model ) [ 2, , drop = FALSE ] ) ),
  2 )
```

### 4. AF4 Method
#### 4.1. Model 2
```{r}
# modeled auxiliary variables: age, sex, country of birth

d_af4 <- d_2010_selected_final %>%
  mutate(
    sex = ifelse( sex == "Female", 1, 0 ),
    Y = identity_change )

summary( d_af4 )
table( d_af4$sex )
table( d_af4$identity_change )
nrow( d_af4 )

set.seed( 123 )
af4_model <- af4( data = d_af4,
                  X_names = c( "sexual_identity_2010" ), 
                  X_values_1 = c( "Non-heterosexual" ),
                  X_values_2 = c( "Heterosexual" ),
                  contrast_type = "ratio",
                  Y_model = Y ~ sexual_identity_2010,
                  W_model = list(
                    sex ~ sexual_identity_2010,
                    age_2010 ~ sexual_identity_2010 + sex,
                    country_of_birth ~ sexual_identity_2010 + sex + age_2010
                    ) )
af4_model

set.seed( 123 )
get_CI( af4_model, n_boot = 1000, type = 'perc' )
```

#### 4.2. Model 3
```{r}
# modeled auxiliary variables: age, sex, country of birth, education

set.seed( 123 )
af4_model <- af4( data = d_af4,
                  X_names = c( "sexual_identity_2010" ), 
                  X_values_1 = c( "Non-heterosexual" ),
                  X_values_2 = c( "Heterosexual" ),
                  contrast_type = "ratio",
                  Y_model = Y ~ sexual_identity_2010,
                  W_model = list(
                    sex ~ sexual_identity_2010,
                    age_2010 ~ sexual_identity_2010 + sex,
                    country_of_birth ~ sexual_identity_2010 + sex + age_2010,
                    education_2010 ~ sexual_identity_2010 + sex + age_2010 + country_of_birth
                    ) )
af4_model

set.seed( 123 )
get_CI( af4_model, n_boot = 1000, type = 'perc' )
```

#### 4.3. Model 4
```{r}
# modeled auxiliary variables: age, sex, country of birth, occupation

set.seed( 123 )
af4_model <- af4( data = d_af4,
                  X_names = c( "sexual_identity_2010" ), 
                  X_values_1 = c( "Non-heterosexual" ),
                  X_values_2 = c( "Heterosexual" ),
                  contrast_type = "ratio",
                  Y_model = Y ~ sexual_identity_2010,
                  W_model = list(
                    sex ~ sexual_identity_2010,
                    age_2010 ~ sexual_identity_2010 + sex,
                    country_of_birth ~ sexual_identity_2010 + sex + age_2010,
                    occupation_2010 ~ sexual_identity_2010 + sex + age_2010 + country_of_birth
                    ) )
af4_model

set.seed( 123 )
get_CI( af4_model, n_boot = 1000, type = 'perc' )
```

#### 4.4. Model 5
```{r}
# modeled auxiliary variables: age, sex, country of birth, education, occupation

set.seed( 123 )
af4_model <- af4( data = d_af4,
                  X_names = c( "sexual_identity_2010" ), 
                  X_values_1 = c( "Non-heterosexual" ),
                  X_values_2 = c( "Heterosexual" ),
                  contrast_type = "ratio",
                  Y_model = Y ~ sexual_identity_2010,
                  W_model = list(
                    sex ~ sexual_identity_2010,
                    age_2010 ~ sexual_identity_2010 + sex,
                    country_of_birth ~ sexual_identity_2010 + sex + age_2010,
                    education_2010 ~ sexual_identity_2010 + sex + age_2010 + country_of_birth,
                    occupation_2010 ~ sexual_identity_2010 + sex + age_2010 + country_of_birth + education_2010
                    ) )
af4_model

set.seed( 123 )
get_CI( af4_model, n_boot = 1000, type = 'perc' )
```

### 5. MICE
#### 5.1 Model 1
```{r}
# modeled auxiliary variable: sexual identity in 2010

mi_dataset <- d_2010_selected_final %>% 
  select( sexual_identity_2010, identity_change ) %>%
  mutate( identity_change = as.factor( identity_change ) )

summary( mi_dataset )
str( mi_dataset )
miss_var_summary( mi_dataset )

imp <- mice( mi_dataset, m = 70, seed = 123, print = FALSE )
summary( imp )
plot( imp )

imp_com <- complete( imp, action = "all", include = FALSE )
summary( imp_com$`1` )

imp_com <- lapply( imp_com, function( df ) {
  df %>%
    mutate( identity_change = as.integer( identity_change ) -1 ) 
  } )
table( imp_com$`1`$identity_change )

design_imp <- svydesign( ids = ~ 1, data = imputationList( imp_com ) )

poisson_robust_model <- with( design_imp,
                              svyglm( identity_change ~ sexual_identity_2010, 
                                      family = quasipoisson( link = "log" ) ) )

pooled <- MIcombine( poisson_robust_model )
summary_result <- summary( pooled )
round(
  exp( summary_result[ 2, c( 1, 3, 4 ) ] ),
  2 )
```

#### 5.2. Model 2
```{r}
# modeled auxiliary variables: sexual identity in 2010, age, sex, country of birth

mi_dataset <- d_2010_selected_final %>% 
  select( sexual_identity_2010, identity_change, age_2010, sex, country_of_birth ) %>%
  mutate( identity_change = as.factor( identity_change ) )

summary( mi_dataset )
str( mi_dataset )
miss_var_summary( mi_dataset )

imp <- mice( mi_dataset, m = 70, seed = 123, print = FALSE )
summary( imp )
plot( imp )

imp_com <- complete( imp, action = "all", include = FALSE )
summary( imp_com$`1` )

imp_com <- lapply( imp_com, function( df ) {
  df %>%
    mutate( identity_change = as.integer( identity_change ) -1 ) 
  } )
table( imp_com$`1`$identity_change )

design_imp <- svydesign( ids = ~ 1, data = imputationList( imp_com ) )

poisson_robust_model <- with( design_imp,
                              svyglm( identity_change ~ sexual_identity_2010, 
                                      family = quasipoisson( link = "log" ) ) )

pooled <- MIcombine( poisson_robust_model )
summary_result <- summary( pooled )
round(
  exp( summary_result[ 2, c( 1, 3, 4 ) ] ),
  2 )
```

#### 5.3. Model 3
```{r}
# modeled auxiliary variables: sexual identity in 2010, age, sex, country of birth, education

mi_dataset <- d_2010_selected_final %>% 
  select( sexual_identity_2010, identity_change, age_2010, sex, country_of_birth, education_2010 ) %>%
  mutate( identity_change = as.factor( identity_change ) )

summary( mi_dataset )
str( mi_dataset )
miss_var_summary( mi_dataset )

imp <- mice( mi_dataset, m = 70, seed = 123, print = FALSE )
summary( imp )
plot( imp )

imp_com <- complete( imp, action = "all", include = FALSE )
summary( imp_com$`1` )

imp_com <- lapply( imp_com, function( df ) {
  df %>%
    mutate( identity_change = as.integer( identity_change ) -1 ) 
  } )
table( imp_com$`1`$identity_change )

design_imp <- svydesign( ids = ~ 1, data = imputationList( imp_com ) )

poisson_robust_model <- with( design_imp,
                              svyglm( identity_change ~ sexual_identity_2010, 
                                      family = quasipoisson( link = "log" ) ) )

pooled <- MIcombine( poisson_robust_model )
summary_result <- summary( pooled )
round(
  exp( summary_result[ 2, c( 1, 3, 4 ) ] ),
  2 )
```

#### 5.4. Model 4
```{r}
# modeled auxiliary variables: sexual identity in 2010, age, sex, country of birth, occupation

mi_dataset <- d_2010_selected_final %>% 
  select( sexual_identity_2010, identity_change, age_2010, sex, country_of_birth, occupation_2010 ) %>%
  mutate( identity_change = as.factor( identity_change ) )

summary( mi_dataset )
str( mi_dataset )
miss_var_summary( mi_dataset )

imp <- mice( mi_dataset, m = 70, seed = 123, print = FALSE )
summary( imp )
plot( imp )

imp_com <- complete( imp, action = "all", include = FALSE )
summary( imp_com$`1` )

imp_com <- lapply( imp_com, function( df ) {
  df %>%
    mutate( identity_change = as.integer( identity_change ) -1 ) 
  } )
table( imp_com$`1`$identity_change )

design_imp <- svydesign( ids = ~ 1, data = imputationList( imp_com ) )

poisson_robust_model <- with( design_imp,
                              svyglm( identity_change ~ sexual_identity_2010, 
                                      family = quasipoisson( link = "log" ) ) )

pooled <- MIcombine( poisson_robust_model )
summary_result <- summary( pooled )
round(
  exp( summary_result[ 2, c( 1, 3, 4 ) ] ),
  2 )
```

#### 5.5. Model 5
```{r}
# modeled auxiliary variables: sexual identity in 2010, age, sex, country of birth, education, occupation

mi_dataset <- d_2010_selected_final %>% 
  select( sexual_identity_2010, identity_change, age_2010, sex, country_of_birth, education_2010, occupation_2010 ) %>%
  mutate( identity_change = as.factor( identity_change ) )

summary( mi_dataset )
str( mi_dataset )
miss_var_summary( mi_dataset )

imp <- mice( mi_dataset, m = 70, seed = 123, print = FALSE )
summary( imp )
plot( imp )

imp_com <- complete( imp, action = "all", include = FALSE )
summary( imp_com$`1` )

imp_com <- lapply( imp_com, function( df ) {
  df %>%
    mutate( identity_change = as.integer( identity_change ) -1 ) 
  } )
table( imp_com$`1`$identity_change )

design_imp <- svydesign( ids = ~ 1, data = imputationList( imp_com ) )

poisson_robust_model <- with( design_imp,
                              svyglm( identity_change ~ sexual_identity_2010, 
                                      family = quasipoisson( link = "log" ) ) )

pooled <- MIcombine( poisson_robust_model )
summary_result <- summary( pooled )
round(
  exp( summary_result[ 2, c( 1, 3, 4 ) ] ),
  2 )
```